#!/usr/bin/env node

var
	fs = require('fs-extra'),
	postcss = require('postcss')
;

fs.emptyDirSync('dist');
fs.copySync('src/index.html', 'dist/index.html');
fs.copySync('src/js', 'dist/js');
fs.copySync('src/img', 'dist/img');
//fs.copySync('src/common/js/optiscroll.js/', 'dist/common/js/optiscroll.js');
css();

function css() {
	var input = fs.readFileSync('src/css/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/css'
		}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/css/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});
}
