#!/usr/bin/env node

var
	fs = require('fs-extra'),
	postcss = require('postcss')
;

css();

function css() {
	var
		inFile = 'src/css/style.scss',
		outFile = 'dist/public/css/style.css',
		sass = require('node-sass')
	;

	console.log('Start Sass on ' + inFile);

	sass.render(
		{
  			file: inFile
		},
		function(err, result) {
			if (err) {
				console.log(err);
			}
			else {
				console.log('Writing ' + outFile + '...');
				fs.writeFile(outFile, result.css, function(err) {
        			if(err) {
          			console.log(err);
        			}
      		});
			}
		}
	);

	/*
	var input = fs.readFileSync('src/css/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/css'
		}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/public/css/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});
	*/
}
